### ISSUE TITLE
vim-cute-python conceal looks too dark in colorscheme molokai

### ISSUE THREAD

**Issue by dynofu** [dyno/sweethome#3]
https://github.com/ehamberg/vim-cute-python
![Screen Shot 2020-01-12 at 4 12 13 PM](https://user-images.githubusercontent.com/31225347/72227916-99ae0680-3556-11ea-9af8-cf28fc18fbbb.png)

**Comment by dyno** [comment]
also https://github.com/dyno/sweethome/blob/master/SpaceVim.d/autoload/myspacevim.vim#L112 `set conceallevel=0` does not seem to work.

**Comment by dynofu** [comment]
`verbose highlight Conceal`
it comes from various places indentLine, jedi, molokai, as it is a global setting really hard to make it right 
https://stackoverflow.com/questions/15071808/vim-conceal-highlight

**Comment by dynofu** [comment]
and more complete python conceal here, https://github.com/alok/python-conceal
